environment:
  image: 'paintedfox/ruby'
  language: ruby

build:
  before:
    - apt-get -y install git
    - gem install bundler
    - bundle install --no-deployment -j 4
  run:
    - bundle exec rake
