environment:
  image: 'localhost:5000/stringer'
  language: 'ruby'
  language_versions: '2.0.0'

build:
  before:
    - bundle install --no-deployment -j 4 --path /mnt/\$(echo \$GIT_URL | sed 's/.*:\(.*\)\.git/\1/')

  run:
    - bundle exec rake
